### ISSUE TITLE
How to reference

### ISSUE THREAD

**Issue by Oliph** [vonsovsky/bert-sentiment#1]
Hi, 
Thank you very much for your code and description. 
I am currently using your code as a base to develop my classifier in a research project. My code should be open on some point and I have a link to your repo to mention you as a source. However, I wanted to know if you have another way to give you credits (other than fork). 
This question assumes you are ok for me to reuse and modify your work, I cannot find a licence. If this assumption is false, please tell me and I will act accordingly.
Regards,

**Comment by vonsovsky** [comment]
Hi Olivier,

thank you for reaching me out. I am glad some people are actually trying to use my code, so you don't need to give me any credits. Good luck with the model and any modifications in the future :-)

Kind regards,
Jakub
